"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Reg = exports.EventBus = exports.Str = exports.Time = exports.Timer = exports.T = exports.Console = void 0;
const dev_1 = require("./dev");
Object.defineProperty(exports, "Console", { enumerable: true, get: function () { return dev_1.Console; } });
Object.defineProperty(exports, "T", { enumerable: true, get: function () { return dev_1.T; } });
Object.defineProperty(exports, "Timer", { enumerable: true, get: function () { return dev_1.Timer; } });
Object.defineProperty(exports, "Time", { enumerable: true, get: function () { return dev_1.Time; } });
Object.defineProperty(exports, "Str", { enumerable: true, get: function () { return dev_1.Str; } });
Object.defineProperty(exports, "EventBus", { enumerable: true, get: function () { return dev_1.EventBus; } });
Object.defineProperty(exports, "Reg", { enumerable: true, get: function () { return dev_1.Reg; } });
